# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Analyze project source
        run: dart analyze

      - uses: subosito/flutter-action@v2.10.0
      - name: Install dependencies
      - run: flutter pub get
      - run: flutter pub global activate dart_code_metrics
      - name: Run metrics
      - run: flutter pub run dart_code_metrics:metrics analyze lib
