name: shops
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  core:
    path: ./core
  data:
    path: ./data
  domain:
    path: ./domain
  core_ui:
    path: ./core_ui


  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.2.0
  flutter_bloc: ^8.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  dart_code_metrics: ^5.7.0

flutter:
  uses-material-design: true
  assets:
    - assets/