name: core
description: A new Flutter package project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=2.19.5 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shops:
    path: ../
  data:
    path: ../data
  domain:
    path: ../domain
  get_it: ^7.2.0
  firebase_analytics: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
